package running.org.running;

interface Constants {
    int SPEED_SETTING_KMH = 0;
    int SPEED_SETTING_MIN_KM = 1;

    int METRONOME_SETTING_OFF = 0;
    int METRONOME_SETTING_ON = 1;

    int MODE_METRONOME_SETTING_CONTINUE = 0;
    int MODE_METRONOME_SETTING_INTERVAL = 1;

    int STEPS_BY_MINUTE_SETTING = 160;
    int STEPS_BY_MINUTE_TIME_SETTING = 120;
    int STEPS_BY_MINUTE_2ND_INTERVAL_SETTING = 0;
    int STEPS_BY_MINUTE_2ND_INTERVAL_TIME_SETTING = 120;
    int REPEAT_METRONOME_SETTING = 1;
}
